apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: app
  replicas: 2
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: miragenn/of-test-app:0.0.3
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /api/healthcheck
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 5
